my:
     name:  dev
spring:
   rabbitmq:
     host: 127.0.0.1
     port: 5672
     username: guest
     password: guest
   redis:
     database: 0
     host: localhost
     port: 6379
     timeout: 6000ms
     jedis:
       pool:
         max-active: 200
         max-wait: -1ms
         max-idle: 10
         min-idle: 0
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/1911?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
     username: root
     password: root
